config/routes.rb
Rails.application.routes.draw do
  resources :friend_requests
  get 'friends/index'
  get 'friends/destroy'
  root to: redirect('/dashboards')

  resources :dashboards
  devise_for :users
  resources :flights do
    get :set_copilot
  end
  resources :airports
  resources :pilots do
    get :add_friend
  end
  resources :friendships


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/flight.rb
class Flight < ApplicationRecord
    has_one :pic_pilot, :class_name => "Pilot", :foreign_key => 'pic_pilot_id'
    has_one :cop_pilot, :class_name => "Pilot", :foreign_key => 'cop_pilot_id'
end

app/controllers/flights_controller.rb
class FlightsController < ApplicationController
  before_action :set_flight, only: [:show, :edit, :update, :destroy]

  # GET /flights
  # GET /flights.json
  def index
    @flights = Flight.all
  end

  # GET /flights/1
  # GET /flights/1.json
  def show
  end

  # GET /flights/new
  def new
    @flight = Flight.new
  end

  helper_method :set_copilot

  # GET /flights/1/edit
  def edit
  end
  def set_copilot
    flight = Flight.find(params[:flight_id])
    if flight == nil
      redirect_to :action => "show", :id => params[:flight_id]
      puts "Flight is nil"
    else
      if flight.cop_pilot_id != nil
        redirect_to :action => "show", :id => params[:flight_id]
        puts "Copilot is not nil"

      else
        flight.cop_pilot_id = current_user.id
        flight.save
        redirect_to :action => "show", :id => params[:flight_id]
      end
    end
    # flight.cop_pilot_id = current_user.id
  end
  def setPilotInCommand
  end

  # POST /flights
  # POST /flights.json
  def create
    @flight = Flight.new(flight_params)

    respond_to do |format|
      if @flight.save
        format.html { redirect_to @flight, notice: 'Flight was successfully created.' }
        format.json { render :show, status: :created, location: @flight }
      else
        format.html { render :new }
        format.json { render json: @flight.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /flights/1
  # PATCH/PUT /flights/1.json
  def update
    
    respond_to do |format|
      if @flight.pic_pilot_id != current_user.id
        format.html { redirect_to @flight, alert: 'You are not authorized to edit this flight' }
        format.json { render :show, status: :unprocessable_entity, location: @flight }
      else
        if @flight.update(flight_params)
          format.html { redirect_to @flight, notice: 'Flight was successfully updated.' }
          format.json { render :show, status: :ok, location: @flight }
        else
          format.html { render :edit }
          format.json { render json: @flight.errors, status: :unprocessable_entity }
        end
      end
      
    end
  end

  # DELETE /flights/1
  # DELETE /flights/1.json
  def destroy
    @flight.destroy
    respond_to do |format|
      format.html { redirect_to flights_url, notice: 'Flight was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_flight
      @flight = Flight.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def flight_params
      params.require(:flight).permit(:from_airport, :to_airport, :pic_pilot_id, :cop_pilot_id, :date, :description, :flightplan, :aircraft)
    end
end

app/helpers/flights_helper.rb
module FlightsHelper
end

app/views/flights/_form.html.erb
<%= form_with(model: flight, local: true) do |form| %>
  <% if flight.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(flight.errors.count, "error") %> prohibited this flight from being saved:</h2>
      <ul>
        <% flight.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :from_airport %>
    <%= form.text_field :from_airport, :maxlenght => 4 %>
  </div>

  <div class="field">
    <%= form.label :to_airport %>
    <%= form.text_field :to_airport %>
  </div>
  <div class="field">
    <%= form.label :aircraft %>
    <%= form.text_field :aircraft %>
  </div>
  <div class="field">
   <%= form.label :date %>
   <%= form.datetime_select :date, :ampm => true, :minute_step => 1 %>
  </div>

  <div class="field">
    <%= form.label :pilot_in_command_id %>
    <%= form.select(:pic_pilot_id, Pilot.all.collect { |s| [s.name, s.lastname, s.id] }, {:include_blank => true, :selected => form.object.pic_pilot_id}) %>

  </div>

  <div class="field">
    <%= form.label :co_pilot_id %>
    <%= form.select(:cop_pilot_id, Pilot.all.collect { |s| [s.name, s.id] }, {:include_blank => true, :selected => form.object.pic_pilot_id}) %>
  </div>

  <div class="field">
    <%= form.label :flightplan %>
    <%= form.text_area :flightplan  %>
  </div>
 <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description  %>
  </div>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/flights/edit.html.erb
<h1>Editing Flight</h1>

<%= render 'form', flight: @flight %>

<%= link_to 'Show', @flight %> |
<%= link_to 'Back', flights_path %>

app/views/flights/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Flights</h1>

<h2>Filter</h2>
<input id="filtertxt" type=text placeholder="Type Anything" onkeyup="search()">

<table id="flights">
  <thead>
    <tr>
      <th>From</th>
      <th>To</th>
      <th>Pilot in command</th>
      <th>Co pilot</th>
      <th>Flightplan</th>
      <th>Description</th>
      <th>Aircraft</th>
      <th>Date</th>

      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @flights.each do |flight| %>
      <tr>
        <td><%= flight.from_airport%></td>
        <td><%= flight.to_airport%></td>
        <%if flight.pic_pilot_id != nil%>
          <td><%= Pilot.find(flight.pic_pilot_id).name%> <%=Pilot.find(flight.pic_pilot_id).lastname%></td>
        <%else%>
          <td>PIC is not yet set!</td>
        <%end%>
         <%if flight.cop_pilot_id != nil%>
        <td><%= Pilot.find(flight.cop_pilot_id).name%> <%=Pilot.find(flight.cop_pilot_id).lastname%></td>
        <%else%>
          <td>F/Ois not yet set!</td>
        <%end%>
        <td><%= flight.flightplan%></td>
        <td><%= flight.description%></td>
        <td><%= flight.aircraft%></td>
        <td><%= flight.date.strftime("%B %d at %I:%M %p")%></td>
        <td><%= link_to 'Details', flight %></td>
        <!-- 
        <td><%= link_to 'Edit', edit_flight_path(flight) %></td>
        <td><%= link_to 'Destroy', flight, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        -->
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Flight', new_flight_path %>

<script>
function tdContainsText(tds){
  let input = document.getElementById("filtertxt");
  let filter = input.value.toUpperCase();
  for(var td of tds){
    let txtValue = td.textContent || td.innerText;
    if((txtValue.toUpperCase().indexOf(filter) > -1)) {
      return true;
    }
  }
  return false;
}
function search() {
  // TODO: Make TH not disappear.
  var table, tr, td, i;
  
  table = document.getElementById("flights");
  tr = table.getElementsByTagName("tr");
  for (i = 1; i < tr.length; i++) {
    tds = tr[i].getElementsByTagName("td");
    if (tdContainsText(tds)) {
        tr[i].style.display = "";
      } else {
        tr[i].style.display = "none";
      }
  }
}
</script>

app/views/flights/new.html.erb
<h1>New Flight</h1>

<%= render 'form', flight: @flight %>
<%= link_to 'Back', flights_path %>

app/views/flights/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>From airport:</strong>
  <%=@flight.from_airport%>
</p>

<p>
  <strong>To airport:</strong>
  <%= @flight.to_airport %>
</p>

<p>
  <strong>Pilot in command:</strong>
  <% if @flight.pic_pilot_id != nil%>
      <td><%= Pilot.find(@flight.pic_pilot_id).name%> <%=Pilot.find(@flight.pic_pilot_id).lastname%></td>
   <% else%>
        <td>PIC is not yet set!<td>
  <% end %>

<p>
  <strong>Co pilot:</strong>
   <% if @flight.cop_pilot_id != nil%>
         <%p @flight.cop_pilot_id %>
        <td><%= Pilot.find(@flight.cop_pilot_id).name%> <%=Pilot.find(@flight.cop_pilot_id).lastname%></td></p>
    <% else%>
        <td>F/O is not yet set!<td>
        <%= link_to "Set", flight_set_copilot_path(@flight), class: "button" %>
    <% end %>

</p>
<p>
  <strong>Flightplan:</strong>
  <td><%= @flight.flightplan%></td></p>
</p>
<p>
  <strong>Description:</strong>
  <td><%= @flight.description%></td></p>
</p>


<%= link_to 'Edit', edit_flight_path(@flight) %> |
<%= link_to 'Back', flights_path %>