config/routes.rb
Rails.application.routes.draw do
  resources :friend_requests
  get 'friends/index'
  get 'friends/destroy'
  root to: redirect('/dashboards')

  resources :dashboards
  devise_for :users
  resources :flights do
    get :set_copilot
  end
  resources :airports
  resources :pilots do
    get :add_friend
  end
  resources :friendships


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/pilot.rb
class Pilot < ApplicationRecord
  has_many :friendships
  has_many :friends, :through => :friendships
end

app/controllers/pilots_controller.rb
class PilotsController < ApplicationController
  before_action :set_pilot, only: [:show, :edit, :update, :destroy]

  # GET /pilots
  # GET /pilots.json
  def index
    @Values = ['Newbie', 'Limited Experience', "Experienced", "Expert Pilot"]

    @pilots = Pilot.all
  end

  def add_friend
    
  end
    
  def remove_friend
      
  end

  # GET /pilots/1
  # GET /pilots/1.json
  def show
    @Values = ['Newbie', 'Limited Experience', "Experienced", "Expert Pilot"]

  end

  # GET /pilots/new
  def new
    @pilot = Pilot.new
    @Values = ['Newbie', 'Limited Experience', "Experienced", "Expert Pilot"]


  end

  # GET /pilots/1/edit
  def edit
    @Values = ['Newbie', 'Limited Experience', "Experienced", "Expert Pilot"]

  end

  # POST /pilots
  # POST /pilots.json
  def create
    @Values = ['Newbie', 'Limited Experience', "Experienced", "Expert Pilot"]

    @pilot = Pilot.new(pilot_params)
    @pilot.user_id = current_user.id
    respond_to do |format|
      if @pilot.save
        format.html { redirect_to @pilot, notice: 'Pilot was successfully created.' }
        format.json { render :show, status: :created, location: @pilot }
      else
        format.html { render :new }
        format.json { render json: @pilot.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pilots/1
  # PATCH/PUT /pilots/1.json
  def update
    respond_to do |format|
      if @pilot.user_id != current_user.id
        format.html { redirect_to @pilot, alert: 'Access denied' }
      else
      if @pilot.update(pilot_params)
        format.html { redirect_to @pilot, notice: 'Pilot was successfully updated.' }
        format.json { render :show, status: :ok, location: @pilot }
      else
        format.html { render :edit }
        format.json { render json: @pilot.errors, status: :unprocessable_entity }
      end
    end
   end
  end

  # DELETE /pilots/1
  # DELETE /pilots/1.json
  def destroy
    @pilot.destroy
    respond_to do |format|
      format.html { redirect_to pilots_url, notice: 'Pilot was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pilot
      @pilot = Pilot.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pilot_params
      params.require(:pilot).permit(:name, :lastname, :hours, :about, :simulator, :user_id, :experience)
    end
end

app/helpers/pilots_helper.rb
module PilotsHelper
end

app/views/pilots/_form.html.erb
<%= form_with(model: pilot, local: true) do |form| %>
  <% if pilot.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(pilot.errors.count, "error") %> prohibited this pilot from being saved:</h2>

      <ul>
        <% pilot.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :lastname %>
    <%= form.text_field :lastname %>
  </div>

  <div class="field">
    <%= form.label :hours %>
    <%= form.text_field :hours %>
  </div>

  <div class="field">
    <%= form.label :about %>
    <%= form.text_area :about %>
  </div>
  <div class="field">
      <% puts @Values%>

    <%= form.label :experience %>
    <%= form.select :experience, @Values, {}, {@Values => params[:pid]} %>
  <div class="field">
    <%= form.label :simulator %>
    <%= form.text_field :simulator %>
  </div>

  <div class="actions ">
    <%= form.submit :class => "btn btn-primary" %>
  </div>
<% end %>

app/views/pilots/edit.html.erb
<h1>Edit your Pilot profile</h1>
<% if current_user.id != @pilot.user_id%>
    <h3>This is not your Profile. Access Denied</h3>
<%else%>
<%= render 'form', pilot: @pilot %>

<%= link_to 'Show', @pilot %> |
<%= link_to 'Back', pilots_path %> |
<%= link_to 'Change passwort',  edit_user_registration_path, :class => 'actions' %> |
<%end%>

app/views/pilots/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Pilots</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Lastname</th>
      <th>Hours</th>
      <th>About</th>
      <th>Simulator</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pilots.each do |pilot| %>
      <tr>
        <td><%= pilot.name %></td>
        <td><%= pilot.lastname %></td>
        <td><%= pilot.hours %></td>
        <td><%= pilot.about %></td>
        <td><%= pilot.simulator %></td>
        <% if pilot.user_id == current_user.id%>
        <!-- <td><%= link_to 'Show', pilot %></td> -->
        <td><%= link_to 'Edit', edit_pilot_path(pilot)%></td> 
        <%else%>
          <%if pilot.friendships.where(:pilot_id => Pilot.find(current_user.id).id, :friend_id  => pilot.id).exists? %>
            <p>You are already Friends</p>
          <%else%>
            <td><%= link_to "Add Friend", friendships_path(:friend_id => pilot), :method => :post %></td> 
        <%end%>
        <!--<td><%= link_to 'Destroy', pilot, method: :delete, data: { confirm: 'Are you sure?' } %></td> -->
        <%end%>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Pilot', new_pilot_path %>

app/views/pilots/new.html.erb
<h1>New Pilot</h1>

<p>Seems it's the first time on this Website. Please create yourself a Pilot Profile.<p>

<%= render 'form', pilot: @pilot %>

<%= link_to 'Back', pilots_path %>

app/views/pilots/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @pilot.name %>
</p>

<p>
  <strong>Lastname:</strong>
  <%= @pilot.lastname %>
</p>

<p>
  <strong>Hours:</strong>
  <%= @pilot.hours %>
</p>

<p>
  <strong>About:</strong>
  <%= @pilot.about %>
</p>

<p>
  <strong>Simulator:</strong>
  <%= @pilot.simulator %>
</p>

<%= link_to 'Edit', edit_pilot_path(@pilot) %> |
<%= link_to 'Back', pilots_path %>